ruby/cours_2/config/routes.rb
Rails.application.routes.draw do
  
  resources :offers
  root 'welcome#home'

  get 'welcome/help'

  get 'welcome/about'

end

ruby/cours_2/app/models/offer.rb
class Offer < ActiveRecord::Base

	# validates :title, presence: true, uniqueness: true, length: ( maximum: 140, message: "too long for a tweet")

	validates_presence_of :title
	validates_uniqueness_of :title
	validates_length_of :title, maximum: 140, message: "too long for a tweet"

	validates_numericality_of :price

	def published
		self.published_at != nil
	end

	def published=(val)
		if val == "1"
			self.published_at = Time.zone.now
		else
			self.published_at = nil
		end
	end

end

ruby/cours_2/app/models/seller.rb
class Seller < ActiveRecord::Base

	has_many :offers

end

ruby/cours_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/cours_2/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :description, :published, :price)
    end
end

ruby/cours_2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  	@offers = Offer.where.not(published_at: nil).order(published_at: "DESC").limit(5)
  end

  def help
  end

  def about
  end
end

ruby/cours_2/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/cours_2/app/helpers/offers_helper.rb
module OffersHelper
end

ruby/cours_2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby/cours_2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cours2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shares/menu" -%>

<%= yield %>

</body>
</html>

ruby/cours_2/app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/cours_2/app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

ruby/cours_2/app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published at</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.description %></td>
        <td><%= offer.published_at %></td>
        <td><%= offer.price %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

ruby/cours_2/app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

ruby/cours_2/app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @offer.published_at %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

ruby/cours_2/app/views/shares/_menu.html.erb
<%= link_to "Home", root_path -%> 

<%= link_to "Help", welcome_help_path -%> 

<%= link_to "About", welcome_about_path -%>

ruby/cours_2/app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

ruby/cours_2/app/views/welcome/help.html.erb
<h1>Welcome#help</h1>
<br>
Need some help ? 
<p>Find me in app/views/welcome/help.html.erb</p>

ruby/cours_2/app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>
<% @offers.each do |offer| %>
	<%= link_to( offer.title, offer_path(offer)) -%>
<% end %>